### ISSUE TITLE
Are you still going to release the tool?

### ISSUE THREAD

**Issue by SweetVishnya** [season-lab/ropdissector#1]

**Comment by dcdelia** [comment]
Absolutely, sorry!

We are currently refactoring ROPDissector to pave the way to the integration with other backends like angr. In the meantime we will publish (I think around the end of this month) the version of the code used in the paper with a few enhancements.

**Comment by dcdelia** [comment]
Hi @SweetVishnya I just uploaded the code for the emulation engine with a few payloads from the Oakland'15 paper to exercise multi-path emulation and CFG reconstruction. Over the next weeks we will be uploading the other payloads on the dedicated repository and provide details on how to run the gadget guessing algorithms over the Adobe Reader versions and PDF payloads from the paper.

Our efforts are currently directed to the refactored version but at the same time we plan on making available soon a thorough description and a reproducible setup for each payload mentioned in the paper so that people may use them for purposes beyond the scope of this project.
